// <auto-generated />
namespace DormDoorMan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Room_string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Room_string));
        
        string IMigrationMetadata.Id
        {
            get { return "201509030131523_Room_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
